idf_component_register(SRCS "main.c" "display.c" "accel.c"
    "game_maze.c" "game_ball_trail.c" "game_glow_ball.c"
    "game_snake.c" "game_breakout.c" "game_dodge.c"
    "game_scroll_text.c" "game_animation.c" "game_tetris.c"
    "game_pong.c" "game_balance.c" "game_catch.c"
    "game_target.c" "game_sokoban.c" "game_marble_race.c"
    INCLUDE_DIRS ".")
